Refatoração do DTO TelegramUpdate
spider-robot-org/spider-robot pull request #47
Opened 2024-02-25 01:06 UTC by Gu-Parlandim

- Esse PR fecha a Issue ``46``
close #46

2024-02-25 13:43 UTC, dansenpir requested changes
Necessário alinhar com a equipe @spider-robot-org/spidey o padrão de nomenclatura de packages.

2024-02-25 13:43 UTC, dansenpir commented on src/main/java/com/bot/spider/dtos/telegram_update/CallbackQueryDTO.java
> +package com.bot.spider.dtos.telegram_update;
@matheusgondra @Jaobuenoh 
Minha única ressalva é o nome do package ser `telegram_update`.
Eu colocaria apenas `telegram` ou então `telegramupdate`.

O que acham?

2024-02-25 13:55 UTC, Gu-Parlandim commented on src/main/java/com/bot/spider/dtos/telegram_update/CallbackQueryDTO.java
> +package com.bot.spider.dtos.telegram_update;
Nesse contexto, o ``telegram`` faz total sentido, mas considerando a complexidade que o projeto pode atingir, escrever todos os pacotes seguindo o padrão ``telegramupdate`` pode dificultar a legibilidade. Por esse motivo, defendo o uso de ``snake_case`` para a nomenclatura dos pacotes. 
vocês decidem se faz sentido.

2024-02-27 23:04 UTC, dansenpir commented on src/main/java/com/bot/spider/dtos/telegram_update/CallbackQueryDTO.java
> +package com.bot.spider.dtos.telegram_update;
> Nesse contexto, o `telegram` faz total sentido, mas considerando a complexidade que o projeto pode atingir, escrever todos os pacotes seguindo o padrão `telegramupdate` pode dificultar a legibilidade. Por esse motivo, defendo o uso de `snake_case` para a nomenclatura dos pacotes. Ou até algo como `telegram.update`.
> 
> vocês decidem se faz sentido.

Eu defendo o uso de `telegram.update`.

2024-02-27 23:05 UTC, dansenpir submitted a review, later dismissed
LGTM!

2024-02-27 23:27 UTC, Jaobuenoh approved these changes
LGTM!

2024-02-27 23:53 UTC, Jaobuenoh approved these changes
LGTM!

2024-02-28 00:17 UTC, matheusgondra commented on src/main/java/com/bot/spider/dtos/telegram_update/CallbackQueryDTO.java
> +package com.bot.spider.dtos.telegram_update;
Concordo com o @dansenpir. Acho que a nomenclatura ficaria melhor como `telegram.update` do que `telegram_update`

2024-02-28 00:33 UTC, matheusgondra reviewed
Não deveríamos usa as classes wrapper (Integer, Long)em vez do tipos primitivos nos DTOs? Ou não faz diferença?

2024-02-28 13:29 UTC, Gu-Parlandim commented
> Não deveríamos usa as classes wrapper (Integer, Long)em vez do tipos primitivos nos DTOs? Ou não faz diferença?

Eu não tenho conhecimento sobre isso, então não sei se há diferença nesse caso. Podemos deixar assim e mudar se surgir algum problema.

2024-02-28 13:51 UTC, merged